[tool.poetry]
name = "cloud-langchain-runnables"
version = "0.1.1"
description = ""
authors = ["Taqi Jaffri <tjaffri@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "*"
langserve = "*"
langgraph = "*"
langchain = "*"
langchain-openai = ">=0.3.3"
langchain-google-genai = "*"
langchain-community = ">=0.3.9"
sse-starlette = "*"
pydantic = "*"
requests = "*"
python-dotenv = "*"
rapidfuzz = "*"
uvicorn = "^0.34.0"

[tool.poetry.group.dev.dependencies]
langgraph-cli = "^0.1.52"
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"