[tool.poetry]
name = "cloud-langchain-runnables"
version = "0.1.1"
description = ""
authors = ["Taqi Jaffri <tjaffri@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "*"
langserve = "*"
langgraph = "*"
langchain = "*"
langchain-openai = ">=0.3.3"
langchain-google-genai = "*"
langchain-community = ">=0.3.9"
sse-starlette = "*"
pydantic = "*"
requests = "*"
python-dotenv = "*"
rapidfuzz = "*"
uvicorn = "^0.34.0"

[tool.poetry.group.dev.dependencies]
langgraph-cli = "^0.1.52"
pytest = "^8.0.0"
pytest-cov = "6.0.0"
black = "^23.10.1"
isort = "^5.12.0"
mypy = "^1.6.1"
flake8 = "^7.1.1"
autopep8 = "^2.3.1"
types-requests = "^2.32.0.20241016"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = "pydantic.*"
strict = true

[[tool.mypy.overrides]]
module = [
    "opentelemetry.*",
    "prometheus_fastapi_instrumentator.*"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --strict-markers"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
]